fix: eslint warnings for v5
webiny/webiny-js pull request #1245
Opened 2020-09-16 15:39 UTC by brunozoric

## Related Issue
eslint warnings in v5- no defined issue

## Your solution
Some variables were removed and some put under eslint disable (where really necessary)

## How Has This Been Tested?
`yarn` -> `yarn build` -> `yarn webiny deploy api --env=local` -> `yarn start`

2020-09-16 17:30 UTC, Ashu96 reviewed
Looks good to me :+1: 
Nicely done @brunozoric  :zap: 

I really liked the simplified `scripts` inside `package.json`. For example,
`"eslint:fix": "yarn eslint --fix",`

2020-09-17 06:41 UTC, doitadrian requested changes
Very nice cleanup 👏 

Just check the three super-tiny comments, and we merge this.

2020-09-17 06:41 UTC, doitadrian commented on package.json
> +    "prettier:fix": "yarn prettier --write",
Looks good, please just use the command here as well:
![image](https://user-images.githubusercontent.com/5121148/93428922-937be100-f8c0-11ea-9ee0-f31e54acec95.png)

2020-09-17 06:41 UTC, doitadrian commented on packages/project-utils/bundling/ssr/buildAppSSR.js
> +    // eslint-disable-next-line
I think we can remove this line / the unused `context` below. I don't see it being used anywhere.

2020-09-17 06:41 UTC, doitadrian commented on packages/project-utils/bundling/ssr/buildAppSSRFromSource.js
> +    // eslint-disable-next-line
Samo as `packages/project-utils/bundling/ssr/buildAppSSR.js`.

2020-09-17 06:54 UTC, doitadrian approved these changes

2020-09-17 06:54 UTC, merged

2020-09-17 06:54 UTC, doitadrian commented
Awesome @brunozoric 👏