feat(app-page-builder): extend button element to support custom click-handlers
webiny/webiny-js pull request #1991
Opened 2021-10-25 09:19 UTC by econtentmaps

Extends button element to allow 'click-handler' plugins to be set as the onClick handler.

## Changes
Added a new click-handler type for the onClick handler plugins. This specifies the button's handler function. plus any parameters the user can set that will be passed to the function.
Created a 'null' clickHandler. This serves two purposes - acts as a simple example and the 'no action' default. Not sure where to put this.
Renamed the 'link' button settings plugin to 'action'
Used Link as the basis for the new settings plugin.
Added a boolean switch to allow the user to select whether the button's action should be link or a clickHandler.
Added new 'clickHandler' options:  1) a drop down that allows the user to select one from a list of all registered 'click-handler' plugins and 2) parameters fields as specified in the plugin's 'parameters' array.
Updated button renderer to parse settings and render the button with either a clickHandler attached to the parent div or the link component.

Both settings and renderer components should correctly deal with buttons with the old 'link' settings.  

## How Has This Been Tested?
Added buttons and created a three custom handlers (both simple console logs and a more involved stripe integration).

## Documentation
Once the PR is accepted I'll be happy to write some documentation for it.

2021-10-29 09:11 UTC, adrians5j requested changes
Here's the initial review @econtentmaps. All in all, looks good, and I think it's gonna be a very nice addition.

BTW could we also see this in action somewhere? Or maybe even better, could you attach a short video of the new feature? 

Thank you again for your time and patience!

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elementSettings/index.ts
> +    console.log("is this where it's being registered?");
Redundant clog. Please remove.

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elements/button/index.tsx
> +    // "pb-editor-page-element-style-settings-link",
Redundant clog. Please remove.

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/types.ts
> +    type: "pb-button-element-click-handler";
Let's make the `type` more in sync with the rest, like `pb-page-element-images-list-component`. So in our case, let's go with `pb-page-element-button-click-handler`.

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/types.ts
> +    handler: Function;
Can we provide a better type here?

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/render/plugins/elements/button/Button.tsx
> +    const plugin = plugins.byName(action.clickHandler);
Wrap in `useMemo` please.

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/render/plugins/elements/button/Button.tsx
> +
Let's just add a quick comment, saying we're preserving backwards compatibility.

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx
> +                        { id: "link", name: "Href Link" },
Let's go with just "Link"

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx
> +    if (element.data?.link && !element.data?.action) {
Let's just add a quick comment, saying we're preserving backwards compatibility

2021-10-29 09:11 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx
> +                    const clickHandlers = plugins.byType<PbButtonElementClickHandlerPlugin>(
Let's wrap in `useMemo`. You can move this up above the `return` line (72).

2021-10-29 09:11 UTC, adrians5j commented on apps/admin/code/src/plugins/pageBuilder/editorPlugins.ts
> +    nullHandler,
I saw there's this `nullHandler` in a couple of places. I'm only going to leave a comment about it here.

To make it a bit simpler, let's remove it, and in the settings component, let's maybe just insert a "None" option manually. 

P.S. I'm aware that the `Select` component is a bit tricky, so maybe you can also try replacing it with Autocomplete component. More than once, I've seen this component working better than Select.

2021-11-09 09:58 UTC, econtentmaps commented on packages/app-page-builder/src/types.ts
> +    handler: Function;
Appreciate some guidance on this one. A handler function will be somewhat arbitrary, is there a better way to type it? Is that the problem you're referring to?

2021-11-18 11:01 UTC, doitadrian commented
Closing this - not relevant anymore.

2021-11-18 11:01 UTC, closed without merging