feat(app-page-builder): rerender page functionality
webiny/webiny-js pull request #2092
Opened 2021-12-03 10:08 UTC by kedrzu

## Changes
Right now, the only way for users to re-render a page is to create a new revision of it and publish it again, which is pretty annoying. This adds a feature of re-rendering the page from the page preview:
![image](https://user-images.githubusercontent.com/2473784/144584670-b66046d6-63b8-43eb-a192-34027392115a.png)

Also there is a new dedicated mutation `pageBuilder.rerenderPage` that you can use in your own scripts.

## How Has This Been Tested?
Manual tests of the new `rerenderPage` mutation and admin app.

2021-12-06 14:05 UTC, kedrzu commented
We decided to remove the button in the UI and leave only GQL mutation. This way we basically restrict that from non-technical users, that will not be aware what is the purpose of that.
For technical users & developers you will still be able to rerender the page with a simple gql query, for example using our embedded GQL playground.

2021-12-07 10:42 UTC, doitadrian approved these changes
Looks good.

2021-12-07 10:44 UTC, doitadrian requested changes

2021-12-07 10:44 UTC, doitadrian commented on packages/api-page-builder/src/graphql/graphql/pages.gql.ts
> +import checkBasePermissions from "@webiny/api-page-builder/graphql/crud/utils/checkBasePermissions";
BTW @kedrzu, check these two imports. Use "~" when importing from package root.

Wouldn't mention this, but CI/CD threw an error related to these two imports. Using "~" will fix it.

2021-12-07 10:45 UTC, doitadrian commented on packages/api-page-builder/src/graphql/graphql/pages.gql.ts
> +import checkBasePermissions from "@webiny/api-page-builder/graphql/crud/utils/checkBasePermissions";
Also, `PageSecurityPermission` can be added to the import statement in line 8.

2021-12-09 07:52 UTC, merged