feat(api-headless-cms): get published or latest revision via manage get
webiny/webiny-js pull request #2266
Opened 2022-03-10 14:14 UTC by brunozoric

## Changes
User can now get either published or latest CMS entry via Manage API get query.
Examples for article:
```
// exact revision
query GetArticle {
    getArticle(revision: "abc#0001") {
        ...
    }
}
// latest revision
query GetArticle {
    getArticle(revision: "abc", type: "latest") {
        ...
    }
}
// latest revision
query GetArticle {
    getArticle(revision: "abc") {
        ...
    }
}
// published revision
query GetArticle {
    getArticle(revision: "abc", type: "published") {
        ...
    }
}
```

## How Has This Been Tested?
Jest and manually.

2022-03-10 14:27 UTC, SvenAlHamad commented
Functionally this meets the required criteria. My only worry is from the DX side that the param name `revision` is a bit misleading as the user is technically providing `entryId`.

2022-03-11 10:24 UTC, Pavel910 requested changes

2022-03-11 10:24 UTC, Pavel910 commented on packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGet.ts
>              "Missing both of GraphQL query arguments: revision and entryId. Must have one.",
```
You must pass a 'revision' or an 'entryId' argument.
```

2022-03-11 10:24 UTC, Pavel910 commented on packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGet.ts
>              `Status cannot be anything other than ${possibleTypes.join(", ")}.`,
```
Status can only be one of the following values:  ${possibleTypes.join(" | ")}.
```


Btw. can we define `status` as an `enum`  so GraphQL takes care of the validation for us?

2022-03-11 10:29 UTC, brunozoric commented on packages/api-headless-cms/src/content/plugins/schema/resolvers/manage/resolveGet.ts
>              `Status cannot be anything other than ${possibleTypes.join(", ")}.`,
It is an enum (check [here](https://github.com/webiny/webiny-js/blob/b934fd6af046cb74af7d080e92bb8e6e89136e30/packages/api-headless-cms/src/content/plugins/schema/baseSchema.ts#L75)). Check in the code is just to be sure string passed is ok.

2022-03-23 11:34 UTC, merged