Feature/event bus prerendering
webiny/webiny-js pull request #2328
Opened 2022-04-15 08:39 UTC by kedrzu

## Changes
Working on staged rollouts requires some changes in how we deal with prerendering. Our new approach uses an event bus instead of directly coupling API and website apps.

- API will not know about the website delivery bucket and delivery CloudFront
- Any prerendering requests will be pushed to the event bus
- Prerendering logic is moved from API to the website and connected to the event bus
- We are moving from a custom DB-based queue to one implemented using AWS SQS for superb parallel processing, automatic deduplication, and auto-retry.

## How Has This Been Tested?
Manual tests.
Is backward compatible, so the user will not have to perform a migration if using the old pulumi architecture.

## Documentation
TBD

2022-04-22 15:08 UTC, doitadrian requested changes
Just some minor nitpicks, but overall the PR looks good.

2022-04-22 15:08 UTC, adrians5j commented on packages/api-prerendering-service-aws/src/flush/flush.ts
> +export type HandlerPlugin = DefaultHandlerPlugin<HandlerContext>;
Can we utilize the `HandlerPlugin` class (from `@webiny/handler` package)?

2022-04-22 15:08 UTC, adrians5j commented on packages/api-prerendering-service-aws/src/flush/flush.ts
> +export type HandlerPlugin = DefaultHandlerPlugin<HandlerContext>;
P.S. The same goes for other handlers.

2022-04-22 15:08 UTC, adrians5j commented on packages/api-prerendering-service-aws/src/render/subscriber.ts
> +            // TODO chunk splitting in case of big amount of events
Is this TODO still necessary? I can see we have some chunking going on below (L85).

2022-04-25 06:08 UTC, kedrzu commented on packages/api-prerendering-service-aws/src/render/subscriber.ts
> +            // TODO chunk splitting in case of big amount of events
You're right, I think it went unnoticed on merge

2022-04-25 06:26 UTC, kedrzu commented on packages/api-prerendering-service-aws/src/flush/flush.ts
> +export type HandlerPlugin = DefaultHandlerPlugin<HandlerContext>;
Sure, but there is not a single example of how to do that. The only one place that uses `HandlerPlugin` from `@webiny/handler` is `handler.test.ts`.

2022-04-29 12:28 UTC, doitadrian approved these changes
@Pavel910 and I gave this another look.

Looks good, we can merge this,

2022-05-11 14:27 UTC, merged