Feat/update user seats
webiny/webiny-js pull request #2492
Opened 2022-06-17 05:19 UTC by Ewan-Roberts

## Changes

Closes [#1247(https://webiny.atlassian.net/browse/WEB-1247)

## How Has This Been Tested?

2022-06-18 06:56 UTC, Ewan-Roberts commented on packages/api-admin-users-cognito/src/createAdminUsers.ts
>                  });
Im pretty sure I need to get the result from this and check the status code, if its failing I need to throw an error here

2022-06-23 17:20 UTC, adrians5j requested changes
Please take a look at my comments.

Initially we discussed a different idea, so let's rearrange this a bit.

2022-06-23 17:20 UTC, adrians5j commented on packages/api-wcp/src/createWcp.ts
> +        // TODO rename geWcpProjectLicenseCacheKey > getWcpProjectLicenseCacheKey
Woah nice one. Will fix it on my side. Thanks!

2022-06-23 17:20 UTC, adrians5j commented on packages/api-admin-users-cognito/package.json
> +    "node-fetch": "3.2.6",
Let's loose this one.

2022-06-23 17:20 UTC, adrians5j commented on packages/api-admin-users-cognito/src/createAdminUsers.ts
> +import { getWcpApiUrl } from "../../wcp/src/urls";
```suggestion
import { getWcpApiUrl } from "@webiny/wcp";
```

2022-06-23 17:20 UTC, adrians5j commented on packages/api-admin-users-cognito/src/createAdminUsers.ts
> +            const wcpProjectEnvironment = getWcpProjectEnvironment();
This wasn't the idea we discussed on the call.

We said we'll load the project environment outside of this file (upon calling `createAdminUsers` method) and we'll send the project environment to this `createAdminUsers` as an arg. This way we're not polluting / introducing a new dependency directly into this method, but we allow for this value to be passed outside of it. 

Let's do it like this.

1. Let's introduce a new `wcp: WcpContextObject` param for `createAdminUsers`
2. On the WcpContextObject side, let's add the incrementSeats / decrementSeats methods, which we'll then call within `createAdminUsers`. Much better than having all this WCP-specific code in a plugin whose purpose is something completely different.

2022-06-24 09:28 UTC, adrians5j commented
Closing this as I will be tackling it in a separate branch.

2022-06-24 09:28 UTC, closed without merging