feat: add Block Editor integration
webiny/webiny-js pull request #2568
Opened 2022-08-08 12:39 UTC by neatbyte-vnobis

## Changes
Add Block Editor page integration

## How Has This Been Tested?
Manual

## Documentation
None

2022-08-10 10:31 UTC, Pavel910 commented
Add a message saying that there are no block categories, and a link to "Create a new category", like we have on the Pages view:
![CleanShot 2022-08-10 at 10 08 45](https://user-images.githubusercontent.com/3920893/183849653-2800a1ef-1519-4fae-a9cc-b5624e3f650d.png)

![CleanShot 2022-08-10 at 10 07 59](https://user-images.githubusercontent.com/3920893/183849495-851b02df-d3c5-4630-be51-a0484c3658c9.png)


Add some padding to create block dialog, same as in the pages view. Feel free to use identical styles that are present in the Pages view, and render category title and a slug underneath:
![CleanShot 2022-08-10 at 10 10 24](https://user-images.githubusercontent.com/3920893/183850124-339617e8-f55a-4a71-96e7-acb219a67aa2.png)

Change the `blockCategory` property to `category`, the `block` prefix is redundant:
![CleanShot 2022-08-10 at 10 14 38](https://user-images.githubusercontent.com/3920893/183850983-6e6b7083-afa3-45f3-969e-9207e4d07019.png)

In Page Builder blocks list, it would be nice if categories could have icons and descriptions. For that we need to expand the Block Categories module to have an icon and a description. There already is an Icon Picker component, see here: `packages/app-headless-cms/src/admin/views/contentModelGroups/IconPicker.tsx`. You can just C/P the component, and we'll worry about reusability later. For a visual example, see `http://localhost:3001/cms/content-model-groups?new=true`

![CleanShot 2022-08-10 at 12 20 02](https://user-images.githubusercontent.com/3920893/183878189-5e840d54-426c-41ab-908d-2f1d391394b9.png)

For `blockCategories`, which you load and generate plugins in the `Editor.tsx`, you really don't need to complicate things with those plugins; you can simply have a Recoil Atom for that. It will be a lot easier to use that data anywhere you need, especially if you create a `useBlockCategories` hook.
<img width="832" alt="CleanShot 2022-08-10 at 12 25 39@2x" src="https://user-images.githubusercontent.com/3920893/183879394-e6b612f4-53fd-46a4-8cc4-189ba489eb37.png">

Regarding the dotted element outline on the block preview img, don't worry about that for now. It's not related to element highlight, that's just how we styled elements in the editor. it's not vital at this point so don't bother with that.

2022-08-11 11:01 UTC, neatbyte-vnobis commented
@SvenAlHamad Please confirm part about "categories could have icons and descriptions"
it requires API changes (2 new fields), so we need to extend scope for these changes.
(or we can create an "improvement" task about it)

2022-08-15 17:54 UTC, SvenAlHamad commented
Hey @neatbyte-vnobis happy for your to invest the extra time to add the two fields. Please just confirm the estimate for this so I can update the milestone on upwork.

2022-08-22 17:09 UTC, Pavel910 requested changes
@neatbyte-vnobis we're almost there. I'll just bother you with a few small things, and hopefully this is the last change request :)

2022-08-22 17:09 UTC, Pavel910 commented on packages/app-page-builder/src/admin/views/PageBlocks/BlocksByCategoriesDataList.tsx
> +                        + Create new block category
Grammar fix: `Create a new block category`

2022-08-22 17:09 UTC, Pavel910 commented on packages/app-page-builder/src/admin/views/PageBlocks/BlocksByCategoriesDataList.tsx
>                      <Typography use="headline5">Please select block category</Typography>
Grammar fix: `Please select a block category`

2022-08-22 17:09 UTC, Pavel910 commented on packages/app-page-builder/src/blockEditor/Editor.tsx
> +                        blockCategories as BlockCategoriesAtomType
As noted in my previous comment, you won't need this, if you move the whole logic of loading block categories into the hook.

2022-08-22 17:09 UTC, Pavel910 commented on packages/app-page-builder/src/blockEditor/Editor.tsx
> +
To make this part reusable, I would move this whole section of `const blockCategories = client.query(...)` into the `useBlockCategories` hook, and then you also don't need to pass blocks to editor state initializer. So you would reuse that hook from both the block editor, as well as the page editor.

It just crossed my mind that you could also just use Apollo cache as state management for block categories, so you won't even need a recoil atom 🤦 . You basically just have the `useQuery` hook wrapped into a `useBlockCategories` hook, and all of a sudden it's reusable everywhere without any state management.

Something like this:
```ts
export const useBlockCategories() {
    const { data } = useQuery(LIST_BLOCK_CATEGORIES);

    return get(data, "pageBuilder.listBlockCategories.data") || [];
}
```

What do you think?

2022-08-23 15:50 UTC, Pavel910 approved these changes
Thanks @neatbyte-vnobis! Feel free to merge this.

2022-08-24 07:28 UTC, merged