Page builder blocks v2: variables for other elements
webiny/webiny-js pull request #2690
Opened 2022-10-17 13:18 UTC by neatbyte-vnobis

## Changes
Add support of other variable types

Notes:
1) [MediumEditor](https://github.com/webiny/webiny-js/compare/page-builder-blocks-v2...page-builder-blocks-v2-variables-for-other-elements?expand=1#diff-31cbe1d931f4cbfca68a1338baf8fe2ce156bff1c43d5b224291954ff1957949) changes are due to "cached" initial state of the rich text editor (it was stored in scope on initial subscribe, and was not updated after that)
2) I have tried to use a makeComposable for image/imageList components (but I not sure if it worth it, please take a look)
3) I have added a "type" property to the variables (as different elements are storing their element value in different places). And now value is "any" (not "string")

## How Has This Been Tested?
Manual

## Documentation
None

2022-10-17 16:39 UTC, Pavel910 requested changes
@neatbyte-vnobis Did a thorough review of the entire PR, and we'll not rush with this one, as there are things to address on an architectural level here, which will make the code nicer, and the logic more decoupled and pluginable.

---

My thinking goes like this. We need to create 2 plugin types:

```ts
/**
 * This plugin is responsible for handling the "create variable" event, when a user wants to create a
 * variable for the selected element of type `elementType`. Elements can support multiple variables, depending on the
 * complexity of their settings, so we need to return an array of PbBlockVariable from the `create` callback.
 *
 * Example: `button` element has a `label` and a `URL`, so it will create 2 variables.
 *
 * Hint: to group variables per element, we can use a dot notation for variable id: `hoEX06c7Xn.label` and `hoEX06c7Xn.url`
 */
export type PbBlockEditorCreateVariablePlugin = Plugin & {
    type: "pb-block-editor-create-variable";
    elementType: string;
    createVariables: (params: { element: PbEditorElement }) => PbBlockVariable[];
};

/**
 * This plugin is responsible for rendering of element variables  of type `elementType`.
 * Example: `button` element will result in 2 inputs being rendered by the `render` callback (label and URL).
 * No parameters are necessary here, as you can always access the active element using hooks.
 */
export type PbEditorPageElementVariableRendererPlugin = Plugin & {
    type: "pb-editor-page-element-variable-renderer";
    elementType: string;
    // If needed for value transformation before the API call.
    getVariableValue(): any; 
    renderVariables: () => ReactNode;
};
```

Please read the code comments before continuing reading.

I intentionally made `createVariables` return an array of variables, since you mentioned that a user might be able to  delete default presets of values when you create a variable set for an element. If you don't need this, convert it to a single variable instead.

The idea is to have a variable plugin for every type of element that needs to support variables. This way we avoid hardcoding of element types, conditional logic, etc. everywhere in the system. Also, this makes it possible for developers to create their own variable plugins for their own custom elements.

I also left several related comments in the actual PR review, so this description should make it all pretty clear. If not, feel free to get in touch.

The location of `PbEditorPageElementVariableRendererPlugin` plugins:
![CleanShot 2022-10-17 at 18 38 34](https://user-images.githubusercontent.com/3920893/196234369-fbdc57e8-be81-4023-a926-6b29189c033c.png)

For `PbBlockEditorCreateVariablePlugin`, create a folder in the `blockEditor/plugins` folder.

To import/register those plugins, use the approach used in the `app-i18n` package: `packages/app-i18n/src/I18N.tsx:22`

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/blockEditor/config/ElementSettingsTabContentPlugin.tsx
> +const elementTypes = ["heading", "paragraph", "image", "images-list", "quote", "list", "button"];
Once you implement my instructions from the PR comment, with new plugins, you'll be able to fetch this dynamically, from plugins.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/blockEditor/config/eventActions/saveBlock/saveBlockAction.ts
> +        const isTextVariable =
Same as the previous comment, once we have individual plugins in place, you'll be able to call those plugins to return a value you need from them, without hardcoding this logic here.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/blockEditor/plugins/elementSettings/CreateVariableAction.ts
> +                            type: element.type,
Continuing the theme here :)
This entire section will be used via `variablePlugin.createVariables({ element })`.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/RichInput.tsx
> +export default RichInput;
There's a better mechanism for this, but let's leave this like this for the time being, until we sort out individual element variable plugins.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/TextInput.tsx
> +export default TextInput;
Same as the previous comment; we'll improve this down the road, for now let's leave it as is.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/VariableSettings.tsx
> +
This entire file needs to be refactored to use the new plugins that I described in the PR comment section. That way we'll achieve a complete separation of concerns here, and won't need to mix different element handling logic in this component.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/VariableSettings.tsx
> +                </div>
Refactor this to look up the appropriate variable plugin using the `element.type`, and call `variablePlugin.renderVariables()` to handle individual element independently.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/VariableSettings.tsx
> +        (value: any, variableId: string, history = false) => {
Extract this into a hook, like `useVariableOnChange` which you can then use in each individual element variable plugin.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elements/imagesList/ImagesList.tsx
> +export default makeComposable(
To answer your question about `makeComposable`, it doesn't hurt. It's great to see you're utilizing the built-in tools 👍 Let's keep this and see if this is the right approach in this situation.

2022-10-17 16:39 UTC, Pavel910 commented on packages/app-page-builder/src/types.ts
>  }
It's probably a good idea to make this interface generic, so you can use the default interface where the variable type is unknown, but use a concrete data type within the rendering logic:

```ts
export interface PbBlockVariable<TValue = any> {
    id: string;
    type: string;
    label: string;
    value?: TValue;
}
```

Then you can use it like this:

```ts
type ButtonVariable = {
  label: string;
  url: string;
}

const variable: PbBlockVariable<ButtonVariable> = element.whatever;

// variable.value.label & variable.value.url are now properly typed and provide autocomplete.
```

2022-11-01 14:49 UTC, neatbyte-vnobis commented
Refactoring was done in pull https://github.com/webiny/webiny-js/pull/2734

2022-11-01 14:49 UTC, closed without merging