fix: fix Image component shadow
webiny/webiny-js pull request #2762
Opened 2022-11-09 15:29 UTC by neatbyte-vnobis

## Changes
Fix issue "Shadow not correctly applied to image"
Closes #2466

## How Has This Been Tested?
Manual

## Documentation
None

2022-11-10 09:02 UTC, SvenAlHamad commented
@neatbyte-vnobis I've tested this one, and the shadow is fixed inside the Page Editor, but if you use the preview option, there it's still the same as before. This tells me that the editor plugin was updated with the fix, but the render (used in the preview) was not.

2022-11-11 09:05 UTC, Pavel910 approved these changes

2022-11-11 16:28 UTC, neatbyte-vnobis commented
@SvenAlHamad I was trying to reproduce this... but I see a shadow on a preview
If you see the issue please do a video recording (so I can follow exact steps)

2022-11-14 10:39 UTC, SvenAlHamad requested changes

2022-11-14 10:39 UTC, SvenAlHamad commented on apps/theme/pageBuilder/styles/elements/image.scss
>    overflow: hidden;
I think this has to be removed as well. Try inserting an image 100x100px in the editor, and assign a shadow with a spread of 5px to the image. You'll see the shadow is only visible on the sides, and gets hidden on the top and bottom. 
<img width="162" alt="image" src="https://user-images.githubusercontent.com/3808420/201639469-98cad485-add6-44ea-b71f-30087ae58e8d.png">

2022-11-21 13:27 UTC, merged