fix: advanced element settings onSave execution
webiny/webiny-js pull request #2803
Opened 2022-11-25 22:09 UTC by neatbyte-vnobis

## Changes
Fix issue "PageBuilder - onSave callback on advanced element settings plugins is not executed".
Closes #2776

## How Has This Been Tested?
Manual

## Documentation
None

2022-11-28 19:24 UTC, neatbyte-vnobis commented
@Pavel910 please review this request

2022-11-28 20:40 UTC, Pavel910 requested changes

2022-11-28 20:40 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/advanced/ElementSettings.tsx
> +        updateElement(merge(element, "data", modifiedFormData || formData));
This is incorrect because we can have multiple plugins for the same `elementType`. A good example is `images-list`, or `pages-list`:
![CleanShot 2022-11-28 at 21 39 20](https://user-images.githubusercontent.com/3920893/204376374-aeb612c6-25f2-4680-b617-757d95dc1e3e.png)


So this needs to be executed with an array of plugins in mind (use `filter` instead of `find`).

The easiest way would be:
```
let modifiedFormData = formData; // this way you don't have to think if there are many or 0 plugins to execute.

// ... iterate over plugins and call each with `modifiedFormData`

updateElement(merge(element, "data", modifiedFormData));
```

2022-11-29 19:53 UTC, Pavel910 approved these changes

2022-11-30 14:54 UTC, merged