feat: add rich text modal for block variable
webiny/webiny-js pull request #2827
Opened 2022-12-06 10:11 UTC by neatbyte-vnobis

## Changes
Implements issue "Add ability to expand the rich text editor from the sidebar"

## How Has This Been Tested?
Manual

## Documentation
None

2022-12-06 13:50 UTC, SvenAlHamad commented
@neatbyte-vnobis - on this one, let's make two adjustments:
1. Let's still keep the ability to edit the paragraph directly in the sidebar, just add an "expand icon" to the variable name, which then opens the modal. Thing is, for shorter text editing it directly in the sidebar is handy. 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/3808420/205929330-b81cea7d-2fc0-4397-aee4-5b967e262a22.png">

2. Let's limit the vertical length of the paragraph input in the sidebar so that it can't expand beyond a certain point, say 250px. I was able to achieve this by adding this css to the input field:
```
    max-height: 250px;
    overflow: scroll;
```

2022-12-09 15:14 UTC, SvenAlHamad commented
@neatbyte-vnobis - this one looks good, just one minor thing. When I open the modal view, is it possible that I'm automatically focused on the text edit field, so that I don't need to explicitly click on it with the mouse, before I can start typing. It's not a crucial feature, but if it's a quick fix, I would like to get it implemented. If it's anything more complicated, let's leave it out for now.

2022-12-15 09:25 UTC, Pavel910 requested changes
A few minor changes and we're done here! 👍

2022-12-15 09:25 UTC, Pavel910 commented on packages/app-page-builder/src/editor/components/MediumEditor/index.ts
> +    forceFocus?: boolean;
Please rename this to `autoFocus`, as we already use that prop name in other components. Just to be consistent.

2022-12-15 09:25 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/RichVariableInput.tsx
> +        color: ${"var(--mdc-theme-text-secondary-on-background)"};
No need for `${}` around `var()`.

2022-12-15 09:25 UTC, Pavel910 commented on packages/app-page-builder/src/editor/plugins/elementSettings/variable/RichVariableInput.tsx
> +import { ReactComponent as ExpandIcon } from "~/admin/assets/expand.svg";
Please use the `@material-design-icons/svg` package for icons. It contains all icons from https://fonts.google.com/icons?selected=Material+Icons so we don't have to manually download SVGs each time, plus it saves on the bundle size. I discovered that package a few months ago and we're now switching to that across the entire admin app.

2022-12-15 10:51 UTC, Pavel910 approved these changes
Thank you!

2022-12-16 14:22 UTC, SvenAlHamad commented
Also, all good from my side on this one.

2022-12-16 14:26 UTC, merged