feat: add element toolbar changes
webiny/webiny-js pull request #2884
Opened 2022-12-20 13:01 UTC by neatbyte-vnobis

## Changes
Implements issues "Adjust the UI of the element list in the left sidebar" and "Click to add vs drag to add"

## How Has This Been Tested?
Manual

## Documentation
None

2022-12-20 18:11 UTC, Pavel910 requested changes
From the code side, the changes are ok.

Functionally, when `Click to add` is clicked, the toolbar should close, but it stays open for some reason.

I would also ask @SvenAlHamad to have a look at the visual implementation, as I'm not the right person to give stylistic advices 😅

2022-12-29 14:27 UTC, SvenAlHamad commented
Just tested this one....I would like to make a small change. Instead of having a width of 320px on the sidebar, let's make it 280px so we save even more space. Other than that, all good.

2023-01-02 10:56 UTC, SvenAlHamad approved these changes

2023-01-03 17:33 UTC, Pavel910 approved these changes

2023-01-10 19:54 UTC, merged