feat: add the ability to duplicate a page
webiny/webiny-js pull request #2890
Opened 2022-12-22 10:19 UTC by neatbyte-vnobis

## Changes
Resolves issue "Add the ability to duplicate a page"

## How Has This Been Tested?
Manual

## Documentation
None

2022-12-29 14:51 UTC, SvenAlHamad commented
@neatbyte-vnobis  - on this one, two minor adjustments:
1. Instead of having "Copy" as the label in the drop down menu, please say "Duplicate"
2. When a duplicated page is created, please select it so that the duplicated page selected in the left menu and its preview is show in the right preview bar

2023-01-02 10:58 UTC, SvenAlHamad commented
This one is good from my end. @Pavel910 - please check how the code implementation looks.

2023-01-03 17:31 UTC, Pavel910 requested changes
@neatbyte-vnobis This solution is problematic  because the `settings` addition to the GraphQL queries is hardcoded, but in reality those settings can be extended with plugins, which means that you will lose information by implementing it this way.

It would be far better to move this whole logic to the API side, and add a `duplicatePage` mutation. It will be cleaner, and easier to handle. Plus, other developers would be able to use this new method programmatically. On the React side, you will just need to call that mutation, and when you get the data back, update the Apollo cache as you're already doing now.

2023-01-18 14:20 UTC, neatbyte-vnobis commented
@Pavel910 please review fix for your comment

2023-01-23 08:36 UTC, adrians5j requested changes
A couple of tiny nit picks, but all in all we're good.
Let's just take care of these and we're good to merge.

Thank you!

2023-01-23 08:36 UTC, adrians5j commented on packages/api-page-builder/src/graphql/graphql/pages.gql.ts
> +                                title: `(Copy) ${page.title}`,
```suggestion
                                title: `${page.title} (Copy) `,
```

2023-01-23 08:36 UTC, adrians5j commented on packages/app-page-builder/src/admin/plugins/pageDetails/header/pageOptionsMenu/PageOptionsMenu.tsx
> +                    showSnackbar(`Duplicated "${page.title}".`);
```suggestion
                    showSnackbar(`The page "${page.title}" was duplicated successfully.`);
```

2023-01-26 18:41 UTC, adrians5j approved these changes

2023-01-26 18:42 UTC, merged