feat: add date to form submission export
webiny/webiny-js pull request #2965
Opened 2023-01-20 11:20 UTC by neatbyte-vnobis

## Changes
Implements issue "Add date/time to the export"

## How Has This Been Tested?
Manual

## Documentation
None

2023-01-23 13:08 UTC, adrians5j requested changes
One minor thing.

Thanks!

2023-01-23 13:08 UTC, adrians5j commented on packages/api-form-builder/src/plugins/graphql/form.ts
> +                            row["Date submitted"] = new Date(submissions[i].createdOn)
Let's use [`date-fns`](https://date-fns.org/) for this.

I saw it [already being used](https://github.com/webiny/webiny-js/blob/dev/packages/db-dynamodb/src/plugins/definitions/DateTimeTransformPlugin.ts) on the backend, so it should not additional size on disk.

2023-01-23 14:24 UTC, SvenAlHamad commented
I've tested this and it's working. However let's just adjust the label so it says "Date submitted (UTC)". Later down the line we'll see how we make sure the dates are translated to the user's timezone.

2023-01-26 19:12 UTC, adrians5j approved these changes
Thanks!

2023-01-26 19:13 UTC, merged