feat: save/render for lexical editor inside page  builder
webiny/webiny-js pull request #3005
Opened 2023-02-03 12:55 UTC by mihajlovco

## Changes
Improved temporary `lexical-editor-pb` structure
Added PeText PLugin

## How Has This Been Tested?
Manually.

2023-02-08 10:56 UTC, Pavel910 requested changes

2023-02-08 10:56 UTC, Pavel910 commented on packages/lexical-editor-pb/src/plugins/PeTextPlugin.tsx
> +        const [{ displayMode }] = useRecoilState(uiAtom);
There are hooks for this, so you don't have to work with recoil directly, check this folder and simplify your code usign these hooks: https://github.com/webiny/webiny-js/tree/dev/packages/app-page-builder/src/editor/hooks

2023-02-08 10:56 UTC, Pavel910 commented on packages/lexical-editor-pb/tsconfig.json
> +      "@webiny/react-composition": ["../react-composition/src"]
These paths are wrong. Compare with the ones aboe, which are correct. Even better, run the script to generate these for you:

```
node scripts/generateTsConfigsInPackages.js
```

2023-02-27 09:26 UTC, Pavel910 requested changes
Last change request @mihajlovco :)

2023-02-27 09:26 UTC, Pavel910 commented on packages/lexical-editor/src/components/Editor/RichTextEditor.tsx
> +                                <ContentEditable style={{ outline: 0, ...editorSizeStyle() }} />
Why call `editorSizeStyle()` 4 times, when you can call it once, assign to a const, and just pass that to all 4 elements?

2023-02-27 10:52 UTC, mihajlovco commented on packages/lexical-editor/src/components/Editor/RichTextEditor.tsx
> +    const sizeStyle = {
@Pavel910 I directly assigned the styles to the variable without calling any method.

2023-02-27 10:55 UTC, Pavel910 approved these changes
Ok, good to be merged!

2023-02-27 11:17 UTC, merged