feat: add other as an option to specific fields
webiny/webiny-js pull request #3031
Opened 2023-02-18 19:21 UTC by neatbyte-vnobis

## Changes
Implement issue "Forms: Add “other” as an option to specific fields"

## How Has This Been Tested?
Manual

## Documentation
None

2023-02-20 11:06 UTC, SvenAlHamad commented
This works well, but I would just suggest one improvement. When we have the "other" option active, can we hide the other input and only show it when the user clicks on the other option in the form and then we display the input and automatically focus on it.

2023-02-21 16:48 UTC, SvenAlHamad commented
I'm good with this implementation.

2023-02-24 12:21 UTC, adrians5j commented
Checking.

2023-02-24 13:22 UTC, adrians5j requested changes
Although the feature doesn't look like it, the PR is not trivial. A lot of stuff to go through and wrap my head around.

Let's start with a couple of comments I left and we'll do additional iterations if needed.

BTW something I also noticed while giving this new feature a try. This "Allow other" text should be a bit smaller:

![image](https://user-images.githubusercontent.com/5121148/221189175-5cf8c1b4-adb5-4275-b34f-9dd5dc4a4cf0.png)

2023-02-24 13:22 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout/fields/Checkbox.tsx
> +                        disabled={!checked({ option: otherOption, value })}
Couldn't we simply render or not render the `OtherInput`, depending on the `checked` call result? A bit confused why we're using `disabled` here and then hiding the field if it's true (via above CSS).

2023-02-24 13:22 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout/fields/Checkbox.tsx
> +                                otherInputRef.current.focus();
Would the following eliminate all these lines of code?
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

Let's try that, but I believe my previous comment would also need to be applied in order for the `autofocus` to work.

2023-02-24 13:22 UTC, adrians5j commented on packages/app-form-builder/src/admin/plugins/editor/formFields/checkboxes.tsx
> +                        <OptionsList form={form} multiple otherOptionSwitch />
```suggestion
                        <OptionsList form={form} multiple otherOption />
```

Let's rename to `otherOption`.

2023-03-06 09:12 UTC, neatbyte-vnobis commented
@adrians5j 
Comments above are fixed, please take a look.

2023-03-07 14:25 UTC, neatbyte-vnobis commented
@adrians5j 
please take a look on this PR
I hope we can merge it (as previous comments are fixed)

2023-03-17 09:53 UTC, adrians5j approved these changes
Nice, thanks @neatbyte-vnobis !

BTW

2023-03-17 09:54 UTC, merged