Automatically Use Custom Domains if Provided
webiny/webiny-js pull request #3072
Opened 2023-03-02 10:40 UTC by adrians5j

## Changes
At the moment, users follow this guide when linking custom domains with their Webiny projects: https://www.webiny.com/docs/infrastructure/additional-resources/connect-custom-domain

The problem with this is that when you start the Admin app, the app is actually still issuing API HTTP requests to the default Cloudfront domain.

This PR addresses this and ensures that if a custom domain was provided, that it's being used in the Admin app, instead of the default Cloudfront domain.

In order to achieve this, we've updated the generation of stack output. This was only required for the API app, but I decided to apply the same change for all apps. So, from now on, for all apps, in the stack output, `appUrl` / `appDomain` and similar variables will always show custom domain, if one was assigned. Additionally, just in case, stack output will still include default Cloudfront domain, via the `cloudFrontAppUrl` / `cloudfrontAppDomain` variables.

## How Has This Been Tested?
Manual.

## Documentation
Changelog. Will updated the mentioned doc article.

2023-03-02 13:09 UTC, Pavel910 approved these changes

2023-03-02 13:45 UTC, jenslauterbach requested changes

2023-03-02 13:45 UTC, jenslauterbach commented on packages/pulumi-aws/src/apps/api/createApiPulumiApp.ts
> +                const domainsOutput = pulumi.output(domains.domains);
As discussed in Slack, the solution should not rely on the `domains` callback.

2023-03-02 13:46 UTC, adrians5j commented on packages/pulumi-aws/src/apps/api/createApiPulumiApp.ts
> +                const domainsOutput = pulumi.output(domains.domains);
Yes! 

Will let you know once this is ready for another look @jenslauterbach!

Thank you 🙏🏻 😊

2023-03-03 10:24 UTC, adrians5j commented
/cypress

2023-03-03 12:18 UTC, adrians5j commented
/cypress

2023-03-03 13:10 UTC, adrians5j commented
/cypress

2023-03-06 10:26 UTC, adrians5j commented
/cypress

2023-03-07 10:09 UTC, Pavel910 approved these changes

2023-03-07 11:46 UTC, merged