feat: page blocks UI improvements
webiny/webiny-js pull request #3106
Opened 2023-03-15 17:50 UTC by neatbyte-vnobis

## Changes
Implements issue "Block selection - UI improvements"

## How Has This Been Tested?
Manual

## Documentation
None

2023-03-15 18:59 UTC, SvenAlHamad commented
@neatbyte-vnobis I've tested this and overall works great, I just noticed one small thing. The two existing buttons have a tooltip on them, and the two new ones we introduced don't. Can you please add the tooltips on them so it's all unified. You can place "Refresh block" and "Edit block" as the tooltip messages. 

<img width="237" alt="CleanShot 2023-03-15 at 18 55 18@2x" src="https://user-images.githubusercontent.com/3808420/225414495-fde987ad-7bc7-487a-88bb-53e8c8aae635.png">

2023-03-20 08:50 UTC, neatbyte-vnobis commented
@SvenAlHamad tooltips were added

2023-03-21 14:15 UTC, adrians5j requested changes
One super minor thingie, other than that, we can merge.

2023-03-21 14:15 UTC, adrians5j commented on packages/app-page-builder/src/pageEditor/config/blockEditing/SearchBlocks.tsx
> +                                    data-testid={"pb-page-details-header-edit-revision"}
Incorrect `testid` name. But feel free to just remove it for now.

2023-03-22 08:34 UTC, neatbyte-vnobis commented
@adrians5j last comment is fixed now

2023-03-22 09:17 UTC, merged