feat: visual adjustments to the page preview panel
webiny/webiny-js pull request #3112
Opened 2023-03-16 18:47 UTC by neatbyte-vnobis

## Changes
Implements issue "Visual adjustments to the page preview panel"

SHOULD BE MERGED AFTER https://github.com/webiny/webiny-js/pull/3103

## How Has This Been Tested?
Manual

## Documentation
None

2023-03-16 19:53 UTC, SvenAlHamad commented
I've tested this one and noticed a small css issue, the dropdown arrow goes outside the dropdown container: 
<img width="443" alt="CleanShot 2023-03-16 at 19 52 10@2x" src="https://user-images.githubusercontent.com/3808420/225737687-49277a89-6657-4c13-946b-d4617c392f35.png">

2023-03-20 08:57 UTC, neatbyte-vnobis commented
@SvenAlHamad I have checked this, and I cannot reproduce the issue.

Maybe you need to rebuild UI on this branch? (there was similar issue in December when you saw a similar bug locally, but after rebuild it was gone). Also please let me know env OS and used browser, if issue is still there.

2023-03-22 09:40 UTC, adrians5j commented
Looks good on my end: 
![image](https://user-images.githubusercontent.com/5121148/226862916-8e13270c-8155-48fe-83c1-cea83b0e964e.png)

2023-03-22 09:59 UTC, adrians5j requested changes
Left a question in the code.

Also, two extra questions.

First one for @SvenAlHamad , should we have a different color for unpublished pages?

At the moment, we use green for published, everything else is yellow.

![image](https://user-images.githubusercontent.com/5121148/226867325-86c50be6-0b73-4e52-ba04-6b6878eb053d.png)

Second question - what happens with statuses when APW is enabled? I mean, will this work with APW enabled? Not sure how statuses work there. Can we expect statuses other than the default ones that come with basic version of Webiny?

2023-03-22 09:59 UTC, adrians5j commented on packages/app-page-builder/src/admin/plugins/pageDetails/header/Header.tsx
> +                    {isSiteRunning && (
Can we rather have the link always shown, but when clicking on it, if the site is not running, display that modal that we show in other places? Like when we click on the View page in dropdown:
![image](https://user-images.githubusercontent.com/5121148/226864557-5e0fb62c-4b29-44dd-a980-a8a088de2f03.png)

2023-03-28 14:37 UTC, SvenAlHamad commented
Let's use a darker grey color for "unpublished" pages. 
As for the APW question @adrians5j - APW still works with those same statuses, it's not affecting them.

2023-04-14 11:16 UTC, adrians5j approved these changes

2023-04-14 11:16 UTC, merged