feat: add Google Analytics Event trigger
webiny/webiny-js pull request #3125
Opened 2023-03-21 17:20 UTC by neatbyte-vnobis

## Changes
Implements issue "Add a trigger for Google Analytics / Google Ad events".
WIP

## How Has This Been Tested?
Manual

## Documentation
None

2023-03-21 17:37 UTC, neatbyte-vnobis commented
@SvenAlHamad @Pavel910 @adrians5j 
I want to confirm/ask few things before you will review this PR.

1) Should users add googletagmanager script somewhere inside `apps/website/public/index.html`?
(I mean manually add a `<script />` tag there with proper Gtag script path with `G-XXX...` id)
Or there is other way to configure Google Analytics via UI?

2) Can I use `@types/gtag.js` package for gtag typescript type?
Currently I declared gtag [here](https://github.com/webiny/webiny-js/pull/3125/files#diff-a9a700ae65579d56b6812085ab4e1a26b20e900dea1a3c8d922d877b7147e34fR15) via stab to bypass typescript type warnings.

3) Also wanted to clarify one thing about UI component:
In requirements there is a reference to SEOSettingsView (`packages/app-page-builder/src/editor/ui/views/SEOSettingsView.ts`) component.
But this is class component with no exposed callback/control interface, so it cannot be reused.
And as I know we are not going to use class components in future.
I have found a component which has similar functionality - it is used for webhook trigger WebhooksRequestsDynamicFieldset (`packages/app-form-builder/src/admin/plugins/editor/triggers/components/WebhooksRequestsDynamicFieldset.tsx`).
It only lacks ability to add new rows after specific row (it always adds to the end of array).
So I decided to use this component as a reference and just add one more field to the rows.
Just let me know if it is ok. Screenshot bellow:
![image](https://user-images.githubusercontent.com/77202393/226694512-54b2568e-a8e9-49d3-a6b9-ae6cc2fbb8f7.png)

2023-03-22 14:30 UTC, SvenAlHamad commented
@neatbyte-vnobis Regarding question #1 - Let's not insert GA into the page automatically. Let's just add a note under that trigger saying: "Make sure you have Google Analytics installed on your website before using this trigger.". 
I'll let Pavel and Adrian comment on other questions.

2023-03-22 14:32 UTC, adrians5j commented
I'll comment on this tomorrow morning (I've already spent my daily PR-reviews time box 😉).

2023-03-23 07:32 UTC, adrians5j commented
Question #2 - sounds good 👍🏻 

Question #3 - also sounds good 👍🏻 

Thank you @neatbyte-vnobis !

2023-03-23 11:40 UTC, neatbyte-vnobis commented
@SvenAlHamad 
Please take a look on 2 images. Which one is looking better for you?
## 1.
![image](https://user-images.githubusercontent.com/77202393/227192589-e234b496-8bac-4257-b80c-86fbd9c88cf8.png)

## 2.
![image](https://user-images.githubusercontent.com/77202393/227192723-7bf6e8ec-39a4-45a0-a75a-99c6c924c70f.png)

2023-03-28 14:34 UTC, SvenAlHamad commented
@neatbyte-vnobis Let's use Option #1, but I would place the message under the button.

2023-03-30 10:03 UTC, neatbyte-vnobis commented
@SvenAlHamad PR was updated according to a comment

2023-05-26 09:05 UTC, neatbyte-vnobis commented
@SvenAlHamad @adrians5j 
Any updates on this PR?
Maybe it worth to merge latest `next` into it and retest it

2023-06-13 07:36 UTC, adrians5j requested changes
Looks good, just need to double-check frontend trigger processing.

2023-06-13 07:36 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout.tsx
> +            const googleAnalyticsEvent = formData.triggers?.["google-analytics-event"];
Trigger processing should not be in the layout. Triggers are handled internally, here:

```
packages/app-form-builder/src/components/Form/FormRender.tsx:173
```

2023-06-15 14:55 UTC, adrians5j approved these changes

2023-06-19 10:48 UTC, merged