feat: introduce block variable support to more elements
webiny/webiny-js pull request #3131
Opened 2023-03-23 10:16 UTC by neatbyte-vnobis

## Changes
Implements issue "Introduce block variable support to all other elements".

## How Has This Been Tested?
Manual

## Documentation
None

2023-03-28 12:32 UTC, SvenAlHamad commented
Hey @neatbyte-vnobis - on this one, I think I might have missed one item in my specification, and that is the variable support for the icon element.

2023-03-30 09:29 UTC, neatbyte-vnobis commented
@SvenAlHamad 
This PR was updated and icon variable support was added (this includes some changes to editor icon component to support it).

Important thing: I have checked the page preview screen and fond out that embed elements are not displaying correctly, now it is fixed.
Also I have added required validation (placeholder, description, and url fields validation), it was missing and it could cause issues without it.

2023-05-26 09:07 UTC, neatbyte-vnobis commented
@SvenAlHamad @adrians5j 
Any updates on this PR?
Maybe it worth to merge latest `next` into it and retest it

2023-06-28 07:36 UTC, adrians5j requested changes
Did a quick manual test. Some notes below ⬇️
 

1. Scratched 1st note. Sorry.

2. When I tried to test Twitter, I received the following err message after I dropped the block onto a new page ⬇️ 
![image](https://github.com/webiny/webiny-js/assets/5121148/2f366a2f-eec1-4052-b5ee-c9b181949a1f)

BTW can confirm the same happened when I tried YT.

2023-06-29 20:07 UTC, adrians5j requested changes
One question here.

2023-06-29 20:07 UTC, adrians5j commented on packages/api-page-builder/src/graphql/elementProcessors/embed.ts
> +        if (value !== undefined && value !== null) {
Why not just do `typeof value === 'string'` here? 🤔

2023-06-30 12:18 UTC, merged