feat: add tabs element
webiny/webiny-js pull request #3184
Opened 2023-04-06 12:11 UTC by neatbyte-vnobis

## Changes
Implements issue "Tabs element".

![image](https://user-images.githubusercontent.com/77202393/230375057-ea67a3c6-650e-4bb0-8855-1834860f61b1.png)

## How Has This Been Tested?
Manual

## Documentation
None

2023-05-05 09:18 UTC, adrians5j requested changes
Checked 15/22 files.

Re code, I left only one comment.

I'm also adding a couple of extra ntoes.

#### 1. Deleting Grid/Cell

If I delete Grid/Cell in the Tab, I can't drag and drop anything to it. I can only click / select element. Check video.

#### 2. Smaller Screens

I see when I enter mobile view, the tabs are just shrunk. Should this be done in a diff way? Maybe question for @SvenAlHamad ?

![image](https://user-images.githubusercontent.com/5121148/236420245-0f4be177-7bd4-4756-aa50-9e41db1a236b.png)


#### 3. Full Controll When Clicking on Tabs

At the moment, users edit the tab label by clicking on the tab, via STYLE tab. But if I want to delete a tab or move it around, I need to click on the Tabs, and then go to ELEMENT tab and do my adjustments there.

![image](https://user-images.githubusercontent.com/5121148/236420589-41ab6b60-2bd8-487f-a542-9a9ba00b6a9a.png)

Seems to me it'd be easier to have everything just on the Tabs level. Less clicking and less confusion.

@SvenAlHamad thoughts?

2023-05-05 09:18 UTC, adrians5j commented on packages/app-page-builder-elements/src/renderers/tabs.tsx
> +        theme.styles.elements["tabs"] = {
Mutating the `theme` object is not advised.

Rather than doing this, let's just create styled components above the `createTabs` and use them below.

2023-05-16 13:09 UTC, SvenAlHamad commented
Regarding:

2. Smaller Screens
-> I agree, having the list of tabs in one row that the user can scroll would be the preference. This solution can also work on larger screens if there are too many tabs that don't fit in one row.

3. Full Controll When Clicking on Tabs
-> This one I was thinking the same, but then when you come to carousel/slider component where you might have additional options on the item level, you will have a different UX for tabs, vs the UX on carousel/slider. I would prefer to have it the same, so I think keeping it as it is might be the better option.

2023-05-26 11:05 UTC, adrians5j requested changes
One minor comment and resolve conflicts. Other than that, we're ready to merge.

2023-05-26 11:05 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elements/tabs/PeTabs.tsx
> +        background-color: var(--mdc-theme-background);
CSS var leftover here.

2023-05-31 15:18 UTC, adrians5j approved these changes

2023-06-09 09:52 UTC, merged