feat: add a date and time fields as field options
webiny/webiny-js pull request #3209
Opened 2023-04-14 08:45 UTC by neatbyte-vnobis

## Changes
Implements issue "Forms: Add a date and time fields as field options".

## How Has This Been Tested?
Manual

## Documentation
None

2023-04-14 08:47 UTC, neatbyte-vnobis commented on packages/app-form-builder/src/admin/plugins/editor/formFields/components/Date.tsx
> +export const Date = ({ fieldFormat, Bind } : { fieldFormat: string, Bind: BindComponent }) => {
@Pavel910 @adrians5j 
Maybe we have a better place where we can save this re-usable component?
If yes, then where should we create it?

2023-05-26 12:00 UTC, adrians5j requested changes
Left some comments.

Also, let's use Date/Time as the name of the field, the same we have in HCMS.

![image](https://github.com/webiny/webiny-js/assets/5121148/4b94eee4-9d6b-48b0-b18a-4528b78d6432)

Finally, let's also back merge `next` and resolve conflicts.

2023-05-26 12:00 UTC, adrians5j commented on packages/app-form-builder/src/types.ts
> +            formFieldData?: {
I saw we're passing this here ```packages/app-form-builder/src/admin/components/FormEditor/Tabs/EditTab/EditFieldDialog/ValidatorsTab.tsx:78```.

Let's rather have the whole `form` param here.
![image](https://github.com/webiny/webiny-js/assets/5121148/fe70772a-1096-4b04-a84c-8cf0e8176cea)

2023-05-26 12:00 UTC, adrians5j commented on packages/app-form-builder/src/render/plugins/validators/lteDate.ts
> +        name: "lteDate",
Here we're using `lteDate`, and below `dateLte` (so, not the same order of the word `date` and `lte`). Can we fix this? The file name is also `lteDate.ts`.

2023-05-26 12:00 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/gteDate.ts
> +            const validValue = `${validator.settings.value}${
This code is confusing. Can you divide it into multiple lines, maybe use specific var names, or at least add a comment.

2023-05-26 12:00 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/gteDate.ts
> +            const regex = /(^\d*:\d*)/gm;
The same goes with this regex. Just naming this `regex` doesn't provide much info on what `/(^\d*:\d*)/gm;` is actually trying to do.

Please do the same for the `lteDate` validator.

2023-05-26 12:00 UTC, adrians5j commented on packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/lteDate.tsx
> +        defaultMessage: "Date/time is later than the provided one.",
This err message is a bit confusing. What is the "provided one" ?

I think, ideally, we'd want to have the exact date being included in the error message. @SvenAlHamad what do you think?

Like "Date must be later than X.". The same would go for "Date must be earlier than X.".

2023-05-26 12:00 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout/fields/Date.tsx
> +const UTC_TIMEZONES = [
Noticed this twice, plus also used in `packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/utils.tsx:16`.

Let's move this array into `@webiny/utils` package (`utcTimezones.ts`).

2023-05-26 12:01 UTC, adrians5j requested changes
Left some comments.

Also, let's use Date/Time as the name of the field, the same we have in HCMS.

![image](https://github.com/webiny/webiny-js/assets/5121148/d1d309fd-dc9e-49c2-a125-9be2f5007ceb)

![image](https://github.com/webiny/webiny-js/assets/5121148/4b94eee4-9d6b-48b0-b18a-4528b78d6432)

2023-05-26 12:19 UTC, SvenAlHamad commented on packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/lteDate.tsx
> +        defaultMessage: "Date/time is later than the provided one.",
Ideally yes as it will help the user to better understand how they can correct this error.

2023-06-09 10:13 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/dateGte.ts
Having just `date` in the name might cause confusion. From what I can see, this does both date and time validation. Let's make the filename reflect that.

2023-06-09 10:13 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/dateGte.ts
> +            const timeValidator = /(^\d*:\d*)/gm;
This variable can go below in the code. Not used immediately.

2023-06-09 10:13 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/dateGte.ts
> +            const validValue = `${validator.settings.value}${
This is also confusing. Let's add comments why we're doing this.

2023-06-09 10:13 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/dateGte.ts
> +            // With this regex we check whether our value is time (11:59) and not a date
Let's be grammatically correct when writing comments. For example, here we're missing dots at the end of each sentence. Sorry to nitpick, but tiny details like these matter to us.

2023-06-09 10:13 UTC, adrians5j commented on packages/api-form-builder/src/plugins/validators/dateGte.ts
Make sure to apply all of the things mentioned in this file in the `dateLte.ts` file and frontend counterpart files too. Thanks!

2023-06-09 10:13 UTC, adrians5j commented on packages/app-form-builder/src/admin/plugins/editor/formFields/components/Date.tsx
Let's rename to `DateTime.tsx`. Thanks!

2023-06-09 10:13 UTC, adrians5j commented on packages/app-form-builder/src/admin/plugins/editor/formFields/dateAndTime.tsx
`dateAndTime` rename to `dateTme`.

2023-06-09 10:13 UTC, adrians5j commented on packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/DateTimeWithTimezone.tsx
> +import { UTC_TIMEZONES } from "@webiny/utils";
Awesome 🚀

2023-06-09 10:13 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout/fields/Date.tsx
> +const UTC_TIMEZONES = [
Awesome 🚀

2023-06-09 10:22 UTC, adrians5j requested changes
A couple of comments.

2023-06-09 10:22 UTC, adrians5j commented on apps/theme/layouts/forms/DefaultFormLayout/Field.tsx
> +import { DateField } from "./fields/Date";
As mentioned in prev comment, should be `DateTimeField`. Thanks!

2023-06-12 08:56 UTC, neatbyte-vnobis commented on packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/lteDate.tsx
> +        defaultMessage: "Date/time is later than the provided one.",
@adrians5j @SvenAlHamad 

Currently in Form Builder validations user CAN specify his own "custom error message" (plain fixed string) for each added validation.
If this "custom error message" is left empty - UI shows `defaultMessage` (also a plain fixed string, just hard coded in the code).

For this `defaultMessage` we can modify plugin TS interface to accept a string of function (this function will return a string with more dynamic error message, for example with max value, etc).

Few things to confirm:
1) maybe it worth to improve `defaultMessage` for all types (integers, strings, etc, not only dates)?

2) how to show a date value for a case with timezone? (plain +1, +2 ??? GMT+2 ??? or also with a timezone name "EEST, Eastern European Summer Time") the easiest way is to use an ISO date format, but it is not "human readable" for common user

3) should we add this more detailed error message to an API validation too??? it has separate implementation inside API package

2023-06-13 10:52 UTC, neatbyte-vnobis commented on packages/app-form-builder/src/admin/plugins/editor/formFieldValidators/lteDate.tsx
> +        defaultMessage: "Date/time is later than the provided one.",
@adrians5j @SvenAlHamad ?

2023-06-15 14:17 UTC, adrians5j approved these changes

2023-06-15 14:18 UTC, adrians5j commented
All good, let's just resolve the CI error and also let's quickly comment on [this](https://github.com/webiny/webiny-js/pull/3209#discussion_r1206702680). Should we write this down for future? @SvenAlHamad @neatbyte-vnobis

2023-06-15 15:04 UTC, SvenAlHamad commented
> All good, let's just resolve the CI error and also let's quickly comment on [this](https://github.com/webiny/webiny-js/pull/3209#discussion_r1206702680). Should we write this down for future? @SvenAlHamad @neatbyte-vnobis

Yeah, let's park that improvement for later.

2023-06-27 12:19 UTC, merged