fix: fix grid issues and after save redirect
webiny/webiny-js pull request #3309
Opened 2023-05-15 11:17 UTC by neatbyte-vnobis

## Changes
Fix issue "Grid width: auto is not getting applied"
Fix issue "State issue when moving a grid"
Fix issue "After save redirect"
Fix issue "The save indicator icon is still to close to the button label"

## How Has This Been Tested?
Manual

## Documentation
None

2023-05-26 11:45 UTC, SvenAlHamad commented
I did a quick test on this one and it seems the issue is resolved now.

2023-05-26 12:05 UTC, adrians5j commented
Quick question - should this be merged in our quarterly release or in the next patch?

2023-05-31 15:43 UTC, adrians5j requested changes
First view.

2023-05-31 15:43 UTC, adrians5j commented on packages/app-page-builder/src/types.ts
> +        source: PbElement | DragObjectWithTypeWithTarget;
Can you explain why we did this change here?

2023-05-31 15:43 UTC, adrians5j commented on packages/app-page-builder-elements/src/utils/index.ts
> +const recreateStyleObject = ({
I want to understand the actual issue better.

From what I understood, you're saying that the `Object.keys` sometimes returns the property names in a different order?

![image](https://github.com/webiny/webiny-js/assets/5121148/d052d9d5-b208-4245-9819-2a908535d703)

2023-05-31 19:36 UTC, neatbyte-vnobis commented on packages/app-page-builder-elements/src/utils/index.ts
> +const recreateStyleObject = ({
No, the issue is not with `Object.keys()`
The issue is with JS `for-in` loop inside @emotion/css lib.
The order of grabbed "property keys" is defined by CHRONOLOGICAL order of added "properties"
(it mean that first added property is grabbed on first iteration, and last added - on last)
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#description

(of cause I ignore properties that uses a NUMBER as a key, as such are not appearing in our code)

When we build element style we loop over element 'modificators', but not all of the have definition for all screensizes in theme. So screen sizes are added to CSS object in order different from theme object.

2023-06-27 13:48 UTC, adrians5j commented on packages/app-page-builder-elements/src/utils/index.ts
> +const recreateStyleObject = ({
Sorry for taking so long to respond to this....

Can you answer me one thing - which exact issue this changes solves?

I was looking at the Notion doc and thought maybe it was [this one](https://www.notion.so/webiny/Grid-issues-and-a-few-minor-bugs-56bdf708bd574530b872a6ceec441692?pvs=4#519607cb5f0041e08a98c05d86f3977d), but not sure.

2023-06-27 14:08 UTC, neatbyte-vnobis commented on packages/app-page-builder-elements/src/utils/index.ts
> +const recreateStyleObject = ({
Exactly this one.
First subtask inside it:
![image](https://github.com/webiny/webiny-js/assets/77202393/118ed121-ca9d-44f7-870d-507334056417)

The problem with styles was not only with a grid but with other elements too.

We can jump into the call, so I can explain issue more clearly.

2023-06-29 10:04 UTC, merged