wip: implementation of the lexical in headless cms
webiny/webiny-js pull request #3316
Opened 2023-05-18 09:54 UTC by mihajlovco

## Changes

Closes #ISSUE_NUMBER

## How Has This Been Tested?

## Documentation

2023-05-31 15:50 UTC, adrians5j requested changes
Left a quick question.

2023-05-31 15:50 UTC, adrians5j commented on packages/lexical-editor-cms-actions/src/components/LexicalCmsEditor.tsx
> +    const { theme } = usePageElements();
I see `usePageElements` here. Not sure whether what we discussed today with Bruno/Monika was something that we'll do later, or we want to do it now?

If you ask me, it's now.

2023-06-06 13:25 UTC, mihajlovco commented on packages/lexical-editor-cms-actions/src/components/LexicalCmsEditor.tsx
> +    const { theme } = usePageElements();
@adrians5j I will implement now

2023-06-08 11:44 UTC, mihajlovco commented
Test1 -  /cypress

2023-06-08 11:47 UTC, mihajlovco commented
/cypress

2023-06-09 08:06 UTC, mihajlovco commented
/cypress

2023-06-12 09:39 UTC, mihajlovco commented
/cypress

2023-06-14 09:22 UTC, mihajlovco commented
/cypress

2023-07-10 08:31 UTC, closed without merging