fix(rte-lexical-renderer) - information about mismatching versions react
webiny/webiny-js pull request #3497
Opened 2023-08-27 21:16 UTC by mihajlovco

With this PR we want to update `README.md` file and inform users how to resolve the problem of mismatching versions between our component which is on version `17.0.2` and the 3rd party custom React app on version `18.x.x`.

## Changes
- Provide a new topic for users to solve this issue in `README.md` file.
- Update documentation for `Verdaccio` commands. (as addition to this PR)

## How Has This Been Tested?
Manually. 
With custom React Application.

Preview of the error 
![image](https://github.com/webiny/webiny-js/assets/82515066/f71b20de-13eb-432f-be50-78443f1de980)

2023-08-28 09:57 UTC, Pavel910 requested changes

2023-08-28 09:57 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +Then run `yarn install`.
You should make it clear that this solution only works for `yarn` projects, not `npm`. In general this whole section is very stiff, and robot-like. There's no natural flow to it. 

> it's possible to encounter errors.

No, it's not a possibility, it's a fact. An error WILL slap you.

> You will see this error message on the screen

When will I see this error? Who will throw the error? Also, that error is just an excerpt from the full error. Show the full error  so developers can quickly compare their error and the one you're documenting.

You should also add a link to the Yarn docs, so people can learn more about resolutions: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

Give it a few more tries, try to make it more human, like you're explaining it to a 4-year old.

2023-08-31 10:28 UTC, Pavel910 requested changes
@mihajlovco much better, has better flow and clear guidance. Just a few comments on grammar/clarity of sentences, and we're done here.

2023-08-31 10:28 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +> You can check the React version dependencies by running following command:
```
You can check which React versions are requested by various dependencies by running the following command
```

2023-08-31 10:28 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +package, and it's dependencies to `v18.x.x`.
```
To resolve this problem, we need to force all dependencies to use the same version of React.
```

2023-08-31 10:28 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +To define the `v18.x.x` of React to all package dependencies that use the old version of React, we need to
To force `yarn` to resolve dependencies across the project to the exact versions we're looking for, use the `resolutions` field in the root `package.json` file.

2023-08-31 10:28 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +After, run `yarn install` in your terminal, and `@webiny/react-rich-text-lexical-renderer` package and inside
Make this sentence shorter:

```
Once the `resolutions` field is defined, run `yarn` to apply the new config.
```

2023-08-31 10:28 UTC, Pavel910 commented on packages/react-rich-text-lexical-renderer/README.md
> +After, run `npm install` in your terminal, and `@webiny/react-rich-text-lexical-renderer` package and inside
Same here:

```
Once the `overrides` field is defined, run `npm install` to apply the new config.
```

2023-08-31 11:14 UTC, mihajlovco commented on packages/react-rich-text-lexical-renderer/README.md
> +> You can check the React version dependencies by running following command:
Changed.

2023-08-31 11:34 UTC, Pavel910 approved these changes

2023-08-31 11:37 UTC, merged