fix: fix inconsistent pb element save-behavior in editor
webiny/webiny-js pull request #3540
Opened 2023-09-20 10:15 UTC by neatbyte-vnobis

## Changes
Resolve issue: [Inconsistent pb element save-behavior in editor](https://github.com/webiny/webiny-js/issues/3510).

1) Page revision now updates after adding an element to the page.
2) Added fallback message to empty elements (`image`, `embeds`) on website.
  ![image](https://github.com/webiny/webiny-js/assets/77202393/c83a6c0d-9afb-4363-9f31-08f9c6349f7c)

## How Has This Been Tested?
Manual

## Documentation
None

2023-11-22 09:09 UTC, adrians5j requested changes
Left a couple of comments.

2023-11-22 09:09 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx
> +        if (data.actionType === actionType) {
Let's double check this. It looks like now I can't save button action settings at all. 
![image](https://github.com/webiny/webiny-js/assets/5121148/6727993d-209f-4746-b471-6c95cc599f2b)

2023-11-22 09:09 UTC, adrians5j commented on packages/app-page-builder/src/editor/recoil/actions/createElement/action.ts
> +        actions: [new UpdateDocumentActionEvent()]
Let's add a comment why this step please.

2023-11-22 09:09 UTC, adrians5j commented on packages/app-page-builder/src/types.ts
> +        newTab?: boolean;
Should the same changes be applied in `packages/app-page-builder-elements/src/renderers/button.tsx:80` ?

2023-11-22 09:09 UTC, adrians5j commented on packages/app-page-builder/src/editor/plugins/elements/button/index.tsx
> +                        action: { actionType: "link", href: "" }
Why this change? Can you just add a comment?

Sorry for nitpkicking, just wanted to be 100% sure I understand what's going on here.

2023-11-23 14:01 UTC, neatbyte-vnobis commented on packages/app-page-builder/src/editor/recoil/actions/createElement/action.ts
> +        actions: [new UpdateDocumentActionEvent()]
Did some more investigation on this.

Currently, Page Builder does not send update document requests to API when an element is added to a page. However, based on my testing, some elements (such as `Heading`, `Paragraph`, `Image`, `Button`, `Pages List` and `Form`) do trigger a document update.

For instance, adding a button element triggers this [updateSettings](https://github.com/webiny/webiny-js/blob/next/packages/app-page-builder/src/editor/plugins/elementSettings/action/ActionSettings.tsx#L44) function, when added to the page. Elements utilizing the Lexical Editor (like `Heading` and `Paragraph`) are triggering this [onChange](https://github.com/webiny/webiny-js/blob/next/packages/lexical-editor-pb-element/src/components/LexicalText.tsx#L44) function.

By adding new `UpdateDocumentActionEvent()` to the `createElementAction` we ensure the document is updated after adding a new element to the page. But since the elements mentioned already trigger a document update on their own, this addition now results in two separate API calls when they are added.

I've tried to fix this for the `Button`, but the fix didn't work as expected, so I reverted these `Button` changes.

2023-12-01 09:32 UTC, neatbyte-vnobis commented
@adrians5j Is this PR ready to be merged?

2025-10-03 16:17 UTC, closed without merging