fix: fix form builder settings after switching to new locale
webiny/webiny-js pull request #3546
Opened 2023-09-21 13:30 UTC by neatbyte-vnobis

## Changes
Resolve issue: [Unable to submit a form in newly created locale](https://github.com/webiny/webiny-js/issues/3135).

Form submission was throwing `"Form Builder" settings not found!` error, since there were no `Form Builder` settings created for the new locale. This also caused the same issue when saving `Form Builder` settings form.
Issue was resolved by triggering `Form Builder` settings creation, when a new `locale` is created.

While fixing this issue I've found that the same is happening for the `Website` settings form, since `Website` settings are also not created for new `locale`. If this fix is ok, then something similar can be done inside `api-page-builder` to create settings after a new `locale` is created.

Also while testing this fix I've noticed that after switching to a new `locale` user is unable to create any pages until a page category with `static` slug is created. Is this expected behavior?

@adrians5j @Pavel910 What do you think?

## How Has This Been Tested?
Manual

## Documentation
None

2023-10-13 11:04 UTC, adrians5j requested changes
Minor stuff.

I agree with PB-related things you mentioned. We can do them all within this PR or via separate PRs, your choice. 🙂

2023-10-13 11:04 UTC, adrians5j commented on packages/api-form-builder/src/plugins/settings/createSettingsForNewLocale.ts
> +export const createSettingsForNewLocale = new ContextPlugin<FormBuilderContext>(context => {
Once a locale has been deleted, let's also delete settings.

2023-10-13 11:04 UTC, adrians5j commented on packages/api-form-builder/src/plugins/settings/createSettingsForNewLocale.ts
> +            locale: locale.code
Do we really need locale here? Wouldn't the current locale automatically be pulled [above](https://github.com/webiny/webiny-js/pull/3546/files#diff-d2594e3f9145cb8635149f194259ac7a98c4cf1181fe220c13ea7065424e7b65R113)?

If there's no really a need to expose locale param, let's maybe not do it.

2023-10-16 13:15 UTC, neatbyte-vnobis commented
@adrians5j While adding similar changes to PB I've noticed that there is no delete option in PB settings crud (FB settings crud [has](https://github.com/webiny/webiny-js/blob/next/packages/api-form-builder/src/plugins/crud/settings.crud.ts#L189) it). Should we add one? Then we will be able to delete settings after the locale is deleted (just like we do in FB now).

2023-10-18 12:52 UTC, adrians5j commented
Yes, let's do it @neatbyte-vnobis . Thanks!

2023-11-21 15:16 UTC, neatbyte-vnobis commented
@adrians5j Currently, the FB/HCMS PR is focused on migrating only `forms` and `submissions`. Changes in this PR are related to FB `settings` (not sure what is current plan for FB `settings` migration to HCMS).

The FB-related changes can be included in the FB/HCMS PR, and, as you've suggested, the PB part can be moved to a separate PR.

2023-12-01 09:37 UTC, neatbyte-vnobis commented
@adrians5j Any updates on this one? Should we move PB changes to a separate PR or leave it as it is?

2025-10-03 16:17 UTC, closed without merging