feat: add wcp check for audit logs
webiny/webiny-js pull request #3580
Opened 2023-10-06 13:45 UTC by neatbyte-vnobis

## Changes
Adds ability to activate and deactivate `Audit Logs` module via `WCP`.

## How Has This Been Tested?
Manual

## Documentation
None

2023-10-13 10:29 UTC, adrians5j requested changes
Left two questions.

2023-10-13 10:29 UTC, adrians5j commented on packages/app-audit-logs/src/plugins/permissionRenderer/index.tsx
> +export const AuditLogsPermissions: React.FC = () => {
Why this approach? Why not just export plugin like we have it with other?

2023-10-13 10:29 UTC, adrians5j commented on apps/admin/src/plugins/index.ts
> -    auditLogsPlugins,
Why was this removed? 🤔

2023-10-13 13:54 UTC, neatbyte-vnobis commented on packages/app-audit-logs/src/plugins/permissionRenderer/index.tsx
> +export const AuditLogsPermissions: React.FC = () => {
I've used the same approach as APW package, that you've suggested to use as reference. [Here](https://github.com/webiny/webiny-js/blob/next/packages/app-apw/src/plugins/permissionRenderer/index.tsx#L27) is APW permission settings plugin and it is registered based on [this](https://github.com/webiny/webiny-js/blob/next/packages/app-apw/src/index.tsx#L45) condition.

2023-10-18 12:42 UTC, adrians5j requested changes
One question remanins.

2023-10-18 12:42 UTC, adrians5j commented on apps/admin/src/plugins/index.ts
> -    auditLogsPlugins,
Question here remains.

2023-10-19 08:04 UTC, neatbyte-vnobis commented on apps/admin/src/plugins/index.ts
> -    auditLogsPlugins,
Please refer to [this](https://github.com/webiny/webiny-js/pull/3580#discussion_r1358301392) answer. Plugin is now registered inside the package based on condition.

2023-10-20 11:58 UTC, adrians5j commented on apps/admin/src/plugins/index.ts
> -    auditLogsPlugins,
Srry, thanks!

2023-10-20 11:58 UTC, merged