fix: fix images after node update
webiny/webiny-js pull request #3594
Opened 2023-10-11 13:58 UTC by neatbyte-vnobis

## Changes
After updating to `aws-sdk v3`, image transform lambdas needed some adjustments to work properly with `sharp`.

## How Has This Been Tested?
Manual

## Documentation
None

2023-10-19 10:36 UTC, Pavel910 requested changes
A few tiny changes to make it all cleaner, and we're done here.

2023-10-19 10:36 UTC, Pavel910 commented on packages/api-file-manager/package.json
> +        "stream"
Let's move the `stream` dep to a global config, since it's a node built-in library. See `.adiorc.js:24`

2023-10-19 10:36 UTC, Pavel910 commented on packages/api-file-manager/src/handlers/transform/optimizeImage.ts
>  // @ts-ignore
Let's get rid of this ignore, and add `"@types/sharp": "^0.32.0"` to `devDependencies`. We'll get proper autocomplete then.

2023-11-06 08:36 UTC, brunozoric approved these changes

2023-11-06 08:48 UTC, merged