feat: expand object + DZ fields via settings parameter >open<
webiny/webiny-js pull request #4153
Opened 2024-06-04 12:25 UTC by ma-schmidt-de

## Changes
The new attribute `open` of interface `CmsModelFieldSettings` controls whether the accordion renderer of objects and dynamic zones are expanded by default.
BREAKING CHANGE: none
Closes #4109

![Screenshot 2024-06-04 at 14 19 45](https://github.com/webiny/webiny-js/assets/19306046/d9b437b2-f0c6-4da7-8837-6d657bf528d8)
![Screenshot 2024-06-04 at 14 20 41](https://github.com/webiny/webiny-js/assets/19306046/e2375633-511b-4d92-9b12-c2992d3a76fa)

## How Has This Been Tested?
Manually.

## Documentation
I'm planning to add a "How to" section below this on in webiny.com/docs:
https://www.webiny.com/docs/headless-cms/extending/content-models-via-code#how-to-set-a-default-value-of-a-field

2024-06-04 12:44 UTC, Pavel910 requested changes
That's a nice PR @ma-schmidt-de, but let's make it even better. The `next` branch now has this new feature called "renderer settings". Check out the draft changelog: https://docs-webiny-com-git-release-5400-webiny.vercel.app/docs/release-notes/5.40.0/changelog#field-renderer-settings

This feature that you've implemented would make much more sense as a renderer settings, not a field setting in general. If you think about it, what does `open` mean on a `boolean` field? So let's move this flag to renderer settings for `dynamicZone` and `object` field renderers. That way each renderer can have its own very specific settings, and the general field definition is not cluttered with unrelated properties.

Here's a reference to how you would use these settings in a renderer: https://github.com/webiny/webiny-js/blob/next/packages/app-headless-cms/src/admin/plugins/fieldRenderers/ref/advanced/components/ReferencesDialog.tsx#L81

And here's how you define new renderer settings, on a renderer level:
https://github.com/webiny/webiny-js/blob/next/packages/app-headless-cms/src/admin/plugins/fieldRenderers/ref/advanced/detailedReferencesRenderer.tsx#L40-L42

The settings will be stored into the `renderer: { name: "...", settings: { ... } }`.

2024-06-04 18:03 UTC, ma-schmidt-de commented
Sounds great, @Pavel910 
I'll look into this and refactor my PR accordingly. 👍

2024-06-05 18:08 UTC, ma-schmidt-de commented
Let me actually open a new PR. I got mixed up a bit with branches in my fork. 🙂

2024-06-05 18:08 UTC, closed without merging

2024-06-05 18:21 UTC, ma-schmidt-de commented
new PR: https://github.com/webiny/webiny-js/pull/4155