feat: expand object & DZ fields via renderer settings
webiny/webiny-js pull request #4155
Opened 2024-06-05 18:21 UTC by ma-schmidt-de

## Changes
Okay, this is the 2nd iteration of the new feature to expand object and dynamic zone HCMS fields by default. According to @Pavel910's [recommendation](https://github.com/webiny/webiny-js/pull/4153#pullrequestreview-2096283885), I'm using the new **renderer settings** feature to define an `open` attribute. If this attribute is set to `true`, the accordion of the object or dynamic zone field is expanded.

BREAKING CHANGE: none
Closes: #4109

## How Has This Been Tested?
Manually, with an in-code content model.
![Screenshot 2024-06-05 at 20 16 10](https://github.com/webiny/webiny-js/assets/19306046/680598d8-906b-47c6-859d-c16fa80d5f50)

## Documentation
We could use this implementation as an example for the section that describes the renderer settings feature.

2024-06-05 18:33 UTC, ma-schmidt-de commented
Testing the no-code content model editor, I saw that my implementation acts as expected. The switch is rendered and a `settings` object is added to the field's renderer.
![Screenshot 2024-06-05 at 20 22 53](https://github.com/webiny/webiny-js/assets/19306046/5be85321-fd00-4810-94f9-aca8a78ae071)

Yet, saving the model the `CmsUpdateContentModel` mutation fails due to the fact, that the default fields `Title`, `Description` and `Image` don't have a `settings` object attached to their field renderer. Is this a known issue? 🤔 
![Screenshot 2024-06-05 at 20 25 01](https://github.com/webiny/webiny-js/assets/19306046/9d3dad1c-0c30-4cdb-a27d-50e181d0c91e)

When I create an empty content model and add an object, dynamic zone or arbitrary field it works just fine.

2024-06-06 07:27 UTC, Pavel910 requested changes
Just one little change here and we're good to go.

On the topic of mutation error, the settings should be either `undefined`, or an object. I will have a look at this right there in your PR, and will push a fix for this, so we expedite merging of this PR.

Thank you!

2024-06-06 07:27 UTC, Pavel910 commented on packages/app-headless-cms/src/admin/plugins/fieldRenderers/object/multipleObjectsAccordion.tsx
> +    const open = getAccordionRenderSettings(field).open;
This is a stylistic thing, but let's use the syntax that we usually use everywhere in our code base:

```ts
const { open } = getAccordionRenderSettings(field);
```

2024-06-06 09:10 UTC, Pavel910 commented
@ma-schmidt-de I pushed a fix for that issue with existing fields, so `settings` will always fall back to `{}` if they don't exist on the field.

2024-06-06 10:04 UTC, ma-schmidt-de commented
@Pavel910 thanks for adding the fix! I polished the code style according to your feedback.
This looks complete to me now. 👍

2024-06-06 10:45 UTC, Pavel910 approved these changes

2024-06-06 10:46 UTC, Pavel910 commented
It's approved, let's wait for CI to finish, and we'll merge it then.

2024-06-06 11:13 UTC, merged

2024-06-06 11:14 UTC, Pavel910 commented
Thanks @ma-schmidt-de for your contribution! Looking forward to more of these!! 🚀