feat(admin-ui): Slider / Range Slider components
webiny/webiny-js pull request #4348
Opened 2024-10-22 13:39 UTC by leopuleo

## Changes
This PR adds two components to the @webiny/admin-ui package:

- `Slider`
- `RangeSlider`

and their form variant.

2024-10-30 10:48 UTC, Pavel910 requested changes

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/RangeSlider/useRangeSlider.ts
> +            omit(props, ["label", "labelPosition"])
Is it possible that your props change, but you want to maintain the state of the Presenter?

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/RangeSlider/useRangeSlider.ts
> +    const [labelsVm, setLabelsVm] = useState(presenter.labelsVm);
This is one of the reasons why it's better to expose a single `presenter.vm`, and have those VMs be the children of a single VM. Example: `vm.sliderVm`, `vm.thumbsVm`... Especially if you look at the useEffect below; you handle all three VMs at once, and never independently.

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/RangeSlider/RangeSliderPresenter.ts
> +    private localValues: number[];
Not sure you even need this property. You can always derive labels from the value of rangeSliderPresenter.

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/RangeSlider/RangeSliderPresenter.ts
> +            onValueChange: this.onValueChange
I'd keep methods outside of VM. Keep them on the presenter itself, and in this case, simply make your `onValueChange` public, and forward the call to the `rangeSliderPresenter` like you're doing now, but remove the `vm` part.

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/Slider/SliderPresenter.test.ts
> +        formSliderPresenter.sliderVm.onValueChange([40]);
Again, just to confirm my previous thoughts: make it `formSliderPresenter.setValue([40]);`

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/RangeSlider/RangeSliderPresenter.ts
> +    private onValueChange = (values: number[]): void => {
A thought on naming: a presenter is an object with methods, and it doesn't know who's calling those methods. So it would make more sense to call this `setValue`, not `onChange`. `onSomething` is more of a UI component/event-based type of naming. A presenter is a standalone, self-sufficient object, and we can remove this notion of "event-driven" from method names.

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/RangeSlider/useRangeSlider.ts
> +    return { sliderVm, thumbsVm };
Here you would also expose methods, not just VMs. For example, we have a `setValue` (ex. onValueChange) method, so the return value would look like `{ vm, setValue }`, which you then forward to the presenter.

2024-10-30 10:48 UTC, Pavel910 commented on packages/ui/src/Slider/Slider.tsx
> +    min?: number | string;
Why is `string` supported?

2024-10-30 10:48 UTC, Pavel910 commented on packages/admin-ui/src/Form/Slider/Slider.tsx
> +    const { sliderVm, thumbVm, labelVm } = useSlider(props);
Here I'd expose a single `vm`, but also expose methods, like `setValue`, etc. and then pass that to components.

2024-10-31 17:05 UTC, leopuleo commented on packages/admin-ui/src/Form/RangeSlider/RangeSliderPresenter.ts
> +    private localValues: number[];
Before the `admin-ui` component supported both controlled and uncontrolled states, like the Radix UI base components. ([Radix UI docs](https://www.radix-ui.com/primitives/docs/components/slider#root), see `value` and `defaultValue`).

Now the `admin-ui` component does not support the `defaultValue` component, developers must provide externally controlled `value` and `onValueChange` callback. Doing so we can derive labels from values.

2024-10-31 17:08 UTC, leopuleo commented on packages/ui/src/Slider/Slider.tsx
> +    min?: number | string;
No idea 😄 it's coming from the previous implementation

2024-11-05 11:23 UTC, merged