New Admin UI - Dialog Component
webiny/webiny-js pull request #4468
Opened 2024-12-31 05:56 UTC by adrians5j

## Changes

Closes #ISSUE_NUMBER

## How Has This Been Tested?

## Documentation

2025-01-16 09:33 UTC, leopuleo requested changes
Nice one, Adrian! 

There are a few minor comments here and there; otherwise, it looks good. Regarding the naming of the props, it’s just my personal opinion, but we can discuss it if you wish.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/CancelButton.tsx
> +export const CancelButton = makeDecoratable("CancelButton", CancelButtonBase);
I would avoid using `makeDecoratable` for "primitive" components. For now, let’s only allow decoration on “public” components.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/ConfirmButton.tsx
> +export const ConfirmButton = makeDecoratable("ConfirmButton", ConfirmButtonBase);
Same here, let's remove `makeDecoratable`

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogContent.tsx
> +    React.ElementRef<typeof DialogPrimitive.Content>,
Do we need the `ref` here? If not, let's remove it.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogContent.tsx
> +    let preventOutsideDismissProps: Pick<
Shall we use `useMemo` here? The `preventOutsideDismiss` won't change so it might have sense.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogDescription.tsx
> +DialogDescription.displayName = DialogPrimitive.Description.displayName;
I would remove this: we are not setting `displayName` for other components (without `ref`). Let's keep it consistent.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogFooter.tsx
> +        <div {...props} className={cn("flex justify-between p-lg pt-md-extra", className)}>
I would implement a check to ensure that `info` and `actions` exist before rendering the outer divs.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogHeader.tsx
> +    let renderedTitle = (
I don't understand this part: why should I render `VisuallyHidden.Root` should wrap a text hidden from the screen but announced by the screen reader. 

In case of a falsy `title`, there is nothing to announce. Am I missing something?

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogHeader.tsx
> +                {showCloseButton !== false && (
I would set `showCloseButton` prop to default `true` instead of` showCloseButton !== false`. But this is a personal choice.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogOverlay.tsx
> +        ref={ref}
Do we need the ref here? If not, let's remove it.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogTitle.tsx
> +DialogTitle.displayName = DialogPrimitive.Title.displayName;
I would remove this: we are not setting `displayName` for other components (without `ref`). Let's keep it consistent.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    titleIcon?: React.ReactElement;
Shall we use `icon` instead of `titleIcon`? Since don't have multiple icons to identify.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    preventOutsideDismiss?: boolean;
Shall we use `disableDismiss` instead of `preventOutsideDismiss`?

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    bodyPadding?: boolean;
Not sure about this prop, but I don't have a strong opinion on it.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    description?: React.ReactNode | string;
`React.ReactNode` already includes `string`, right? No need to add it.

2025-01-16 09:33 UTC, leopuleo commented on packages/admin-ui/src/Heading/Heading.tsx
> +export type HeadingTags = "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "div";
Why do we need to add `p` and `div` tags?

2025-01-16 09:33 UTC, leopuleo commented on packages/app-admin-rmwc/src/modules/Overlays/Dialog.tsx
> +                    <DialogAccept
:heart:

2025-01-16 10:40 UTC, adrians5j commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    titleIcon?: React.ReactElement;
Makes sense...  although still.. `Alert.Icon` sounds a bit confusing to me when compared to `Alert.TitleIcon`. I mean... the question that pops up in my head: "Is this an icon that can be used anywhere in the dialog or? 🤔".

2025-01-16 10:49 UTC, adrians5j commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    preventOutsideDismiss?: boolean;
What about just `canDismiss` or `dismissable` ? I'm like always trying to name props in a positive way, not as a negation. 

So basically, instead of doing `preventOutsideDismiss={true}`, users would do `dismissable={false}`. Wdyt?

2025-01-16 10:50 UTC, adrians5j commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    bodyPadding?: boolean;
Not sure as well. But added it without much thinking TBF / to just move on. It _is_ essentially the implementation of the idea we discussed with Kreso.

2025-01-16 10:51 UTC, adrians5j commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    description?: React.ReactNode | string;
Nice one, ty!

2025-01-16 10:52 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/CancelButton.tsx
> +export const CancelButton = makeDecoratable("CancelButton", CancelButtonBase);
Actually, I followed the rule "whatever is exposed to the user, we can make it decoratable". Did I get the rule wrong then? 😀

2025-01-16 10:52 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/ConfirmButton.tsx
> +export const ConfirmButton = makeDecoratable("ConfirmButton", ConfirmButtonBase);
Same as with Cancel. :)

2025-01-16 10:55 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogContent.tsx
> +    React.ElementRef<typeof DialogPrimitive.Content>,
Good point!

2025-01-16 11:30 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogContent.tsx
> +    let preventOutsideDismissProps: Pick<
Good point.

2025-01-16 11:35 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogContent.tsx
> +    React.ElementRef<typeof DialogPrimitive.Content>,
Actually, it's needed. Without it, I start receiving:

> Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Looks like Radix needs it.

2025-01-16 11:36 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogDescription.tsx
> +DialogDescription.displayName = DialogPrimitive.Description.displayName;
Ah cool.

2025-01-16 11:38 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogFooter.tsx
> +        <div {...props} className={cn("flex justify-between p-lg pt-md-extra", className)}>
Sounds good.

2025-01-16 11:42 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogHeader.tsx
> +                {showCloseButton !== false && (
This way I'm explicitly not-rendering only if `false` was passed. Every other value is assumed as true. Saves me the trouble of defining default values in props in multiple components (parent Dialog and this one). I know it's not like this component will be used standalone, but still, less to think about. :)  

And it's probably also just a personal choice as you said. ☺️

2025-01-16 11:50 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogHeader.tsx
> +    let renderedTitle = (
Hey man.... I don't know what happened, but I remember without all of these weird things I did, Radix would complain about "description" / "title" missing. And to use VisuallyHidden in this case. Something along those lines.

In any case, I did more testing, and realized this new version of the code also works without any warnings in the console. 🤷‍

I'm thinking maybe it was the package upgrade I did that fixed this. In any case, thanks for noticing this, I believe now it should be much clearer.

2025-01-16 11:52 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogOverlay.tsx
> +        ref={ref}
Radix complains when ref is ommited: 

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

2025-01-16 12:41 UTC, adrians5j commented on packages/admin-ui/src/Dialog/components/DialogTitle.tsx
> +DialogTitle.displayName = DialogPrimitive.Title.displayName;
Nice one.

2025-01-16 15:15 UTC, adrians5j commented on packages/admin-ui/src/Heading/Heading.tsx
> +export type HeadingTags = "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "p" | "div";
Removed it. I think I needed it at one point, but ultimately looks like this is no longer the case. 

Thanks!

2025-01-20 13:13 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    bodyPadding?: boolean;
Let's go ahead and leave this as it is for now.

2025-01-20 13:14 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    preventOutsideDismiss?: boolean;
Ok, I like the positive-naming approach. Let's proceed with `canDismiss` or `dismissable`

2025-01-20 13:20 UTC, leopuleo commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    titleIcon?: React.ReactElement;
As I see it, it's similar to the `description` prop: they are very similar in how they are used inside the component, and we are not referring to it as `titleDescription`.

2025-01-20 13:21 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/CancelButton.tsx
> +export const CancelButton = makeDecoratable("CancelButton", CancelButtonBase);
You are right, sorry...I missed the fact the component is "public" 😄

2025-01-20 13:23 UTC, leopuleo commented on packages/admin-ui/src/Dialog/components/DialogHeader.tsx
> +                {showCloseButton !== false && (
Ok, let's leave it like it is 👍

2025-01-20 15:16 UTC, adrians5j commented on packages/admin-ui/src/Dialog/Dialog.tsx
> +    titleIcon?: React.ReactElement;
Went with just `icon`.

2025-01-20 15:43 UTC, merged